apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: friends-pvc
spec:
  resources:
    requests:
      storage: 500Mi
  accessModes:
    - ReadWriteMany
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: friends-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: friends-postgres
  template:
    metadata:
      labels:
        app: friends-postgres
    spec:
      containers:
      - name: friends-postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret-config
                key: password
        volumeMounts:
          - mountPath: /var/opt/postgresql/data
            name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: friends-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: friends-postgres-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: friends-postgres
  ports:
    - name: friends-postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: friends-postgres-nodeport-service
spec:
  type: NodePort
  selector:
    app: friends-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432